# Site settings
title:          Phim Mới | Phim hay | Xem phim nhanh | Xem phim online | Phim HD vietsub hay nhất
description:    "Xem phim mới miễn phí nhanh chất lượng cao. Xem Phim online Việt Sub, Thuyết minh, lồng tiếng chất lượng HD. Xem phim nhanh online chất lượng  ..."
baseurl:        "/"
url:            "https://phim.netlify.com"

# Author
author:
  name:         black048
  email:        wibu048@gmail.com

# Build settings
markdown:       kramdown

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:title.html
paginate:       18
paginate_path: "/page-:num/"

# Google Analytics
ga-lite: UA-133437491-5


